theme: jekyll-theme-hacker
title: Breaking Ground on a GitHub Page for CSHU-250
description: Also, I am quite aware that I am a living parody, thank you.

## Initial Heading

### Faffing About


###### CONCLUDED

