theme: jekyll-theme-hacker
title: Breaking Ground on a GitHub Page for CSHU-250
description: Also, I am quite aware that I am a living parody, thank you.

## Initial Heading
I appreciate the fact that the name Markdown is absolutely a pun on Markup. I would be curious to know if they are direct competitors or not.

### Faffing About
I would be very interested to know how to make use of contractions and the like. As is usually the case, some punctuation is reserved. But I suppose there will be time for 
that eventually.

[Drill Link](http://Twitter.com/MakeItRayn0r)
That *should* link to my twitter. No need to waste your time.

# Conclusion
This class has been all right. I appreciate getting an opportunity to screw around with this stuff and get my feet wet. Also, probably wiser to leave it online instead of remote.
Some of these 1-cred CSHU courses with lectures are more of a pain in the backside.
